{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1473774138,"rating":0,"authorHandle":"adiIspas","modificationTimeSeconds":1473774138,"id":47086,"title":"\u003cp\u003ePython 3 RUNTIME ERROR\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eI tried to upload a source in Python but I got it:\u003c/p\u003e\u003cp\u003eTime: 30 ms, memory: 0 KB Verdict: RUNTIME_ERROR\u003c/p\u003e\u003cp\u003eCode:\u003c/p\u003e \u003cpre\u003e\u003ccode\u003enumbers \u003d int(input())\n\na \u003d []\nb \u003d []\n\nfor i in range(0, numbers):\n    a.append(int(input()))\n\nfor i in range(1, numbers):\n    b.append(a[i - 1] + a[i])\n\nb.append(a[numbers - 1])\nprint(b)\n\u003c/code\u003e\u003c/pre\u003e\u003c/div\u003e","tags":["python 3","runtime error"]}}