{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1462513422,"rating":6,"authorHandle":"duongtnhat","modificationTimeSeconds":1462513600,"id":44727,"title":"\u003cp\u003eProblem with python??\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003e\u003ca href\u003d\"/contest/670/submission/17754492\" title\u003d\"Submission 17754492 by duongtnhat\"\u003e17754492\u003c/a\u003e Here is my solution for \u003ca href\u003d\"/contest/670/problem/D1\" title\u003d\"Codeforces Round 350 (Div. 2)\"\u003e670D1 - Magic Powder - 1\u003c/a\u003e\u003c/p\u003e\u003cp\u003eI dont know why it catch time limit exceeded on test 148. And then, I try g \u003d l + (r-l+1) / 2, it is accepted? (g is midle in binary search), Im a newbie in python, and sorry for my bad in English\u003c/p\u003e\u003c/div\u003e","tags":["coding","python 2","#contest"]}}