{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1439163262,"rating":0,"authorHandle":"ubeatlenine","modificationTimeSeconds":1439163262,"id":19689,"title":"\u003cp\u003eLocal output doesn\u0027t match codeforces output?\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eHello codeforces!\u003c/p\u003e\u003cp\u003eI have been working on \u003ca href\u003d\"//codeforces.com/problemset/problem/567/C\"\u003eround #pi Div. 2 problem C\u003c/a\u003e. Currently, I am getting WA on test case #7. The strange thing is, I have duplicated the failing test case on my local machine, and my program gives the correct answer, so now I am not sure what to do. You can find the submission \u003ca href\u003d\"//codeforces.com/contest/567/submission/12430534\"\u003ehere\u003c/a\u003e. I would love to be able to duplicate this failure locally, does anyone know how to do that?\u003c/p\u003e\u003cp\u003eThanks!\u003c/p\u003e\u003c/div\u003e","tags":[]}}