{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1474737037,"rating":0,"authorHandle":"Ali_BM","modificationTimeSeconds":1474737092,"id":47333,"title":"\u003cp\u003eRuntime error in python 2\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eHello every one . I have solved a problem with python 2 but code forces shows me runtime error . could you please tell me how i can solve this problem with code forces ? The problem is : 25A This is my code : \u003c/p\u003e \u003cpre\u003e\u003ccode\u003en \u003d input()\narray \u003d []\na1 \u003d []\na2 \u003d []\nfor i in range(0,n) :\n\ttemp \u003d input()\n\tarray.append(temp)\n\tif array[i] % 2 :\n\t\ta1.append(i)\n\telse :\n\t\ta2.append(i)\nif len(a1) \u0026lt; len(a2) :\n\tprint a1[0] + 1, \u0026quot;\\n\u0026quot;\nelse :\n\tprint a2[0] + 1, \u0026quot;\\n\u0026quot;\n\u003c/code\u003e\u003c/pre\u003e\u003c/div\u003e","tags":["runtime error","python 2","python"]}}