{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1503117241,"rating":-1,"authorHandle":"AhsanRomeo","modificationTimeSeconds":1503117241,"id":53947,"title":"\u003cp\u003eGetting RTE on Python !!!\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003eI am new to Python. I have already solved this \u003ca href\u003d\"/contest/377/problem/A\" title\u003d\"Codeforces Round 222 (Div. 1)\"\u003e377A - Maze\u003c/a\u003e by DFS with C++ ( \u003ca href\u003d\"/contest/377/submission/29469941\" title\u003d\"Submission 29469941 by AhsanRomeo\"\u003e29469941\u003c/a\u003e ). To practice Python, I implemented the same approach with Python ( \u003ca href\u003d\"/contest/377/submission/29553044\" title\u003d\"Submission 29553044 by AhsanRomeo\"\u003e29553044\u003c/a\u003e ) but getting RTE on test 7. Please help me.\u003c/p\u003e\u003cp\u003eThanks in advance :-)\u003c/p\u003e\u003c/div\u003e","tags":["pyhton","runtime error","practice"]}}