{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1494988568,"rating":1,"authorHandle":"uttom","modificationTimeSeconds":1494988741,"id":52037,"title":"\u003cp\u003eRuntime Time Error due to customize in sort function\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003e\u003ca href\u003d\"//codeforces.com/contest/808/problem/E\"\u003eProblem\u003c/a\u003e Accepted \u003ca href\u003d\"//codeforces.com/contest/808/submission/27170821\"\u003eSolution\u003c/a\u003e Runttime error \u003ca href\u003d\"//codeforces.com/contest/808/submission/27170321\"\u003ecode\u003c/a\u003e\u003c/p\u003e\u003cp\u003eI sort some value that are stored in some vector(2D) lst[]\u003c/p\u003e \u003cpre\u003e\u003ccode\u003ebool cmp(i64 a,i64 b){\n return a\u0026gt;b\n}\nsort(lst[i].begin(),lst[i].end(),cmp)\n\nThis is my accepted code customize sort\n\u003c/code\u003e\u003c/pre\u003e\u003cp\u003eIn second code\u003c/p\u003e \u003cpre\u003e\u003ccode\u003ebool cmp(i64 a,i64 b){\n return a\u0026gt;\u003db\n}\nsort(lst[i].begin(),lst[i].end(),cmp)\nThis code got Runtime error.\n\u003c/code\u003e\u003c/pre\u003e\u003cp\u003eMy question is that if my customize funtion in 2nd code is\u003c/p\u003e\u003cp\u003ewrong then My verdict will be Wrong but why Runtime Error. Thanks in Advance.\u003c/p\u003e\u003c/div\u003e","tags":["mysterious runtime error"]}}