{"status":"OK","result":{"originalLocale":"en","allowViewHistory":true,"creationTimeSeconds":1476604911,"rating":13,"authorHandle":"maximus12793","modificationTimeSeconds":1476604911,"id":47795,"title":"\u003cp\u003epython 2.7 runtime_error??\u003c/p\u003e","locale":"en","content":"\u003cdiv class\u003d\"ttypography\"\u003e\u003cp\u003e\u003ca href\u003d\"//codeforces.com/contest/378/submission/21474186\"\u003ehttp://codeforces.com/contest/378/submission/21474186\u003c/a\u003e\u003c/p\u003e\u003cp\u003eI have submitted the analogous code in c++ and it worked fine. Is there some reason why this does not work even having set the recursion limit to 20k? I have every time the time and memory is well within limit when it crashes. any ideas?\u003c/p\u003e\u003c/div\u003e","tags":["python 2","runtime error","speed"]}}